eureka:
  client:
    serviceUrl:
      defaultZone: http://sp-discovery:8761/eureka/
  instance:
    preferIpAddress: true

endpoints:
  restart:
    enabled: true

zuul:
  routes:
    sp-facebook:
      path: /api/facebook/**
      serviceId: sp-facebook
    sp-github:
      path: /api/github/**
      serviceId: sp-github

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO